version: '3'

services:
#  db:
#    image: postgres:13.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    env_file:
#      - ..//backend/.env
#    restart: always

  backend:
#    image: skyflyer1/foodgram:latest
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    restart: always
    volumes: 
#      - ../backend/:/app/result_build/
      - static_value:/app/static/
      - media_value:/app/media/
#      - redoc:/app/api/docs/
#    depends_on:
#      - db
    env_file:
      - ..//backend/.env

  frontend:
#    image: skyflyer1/foodgram-frontend:latest
#    volumes:
#      - ../frontend/:/app/result_build/
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
#      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
#  postgres_data:
  static_value:
  media_value:
