# Generated by Django 3.2.14 on 2022-12-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsforrecipes',
            options={'ordering': ['-id'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты для рецептов'},
        ),
    ]
