# Generated by Django 3.2.14 on 2022-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientsforrecipes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsforrecipes',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты для рецептов'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=10, verbose_name='Единица измерения'),
        ),
    ]
